plugins {
    id 'java'
    id 'application'
}

java {
    sourceCompatibility = JavaVersion.toVersion(17)
    targetCompatibility = JavaVersion.toVersion(17)
}

repositories {
    mavenCentral()
}

application {
    mainClass = 'edu.odu.cs.cs350.App'
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.0'
    testImplementation 'org.hamcrest:hamcrest:3.0'
    testImplementation 'junit:junit:4.13.2' // or the latest JUnit 4 version
    testImplementation 'org.junit.jupiter:junit-jupiter:5.7.0'
    testImplementation 'org.hamcrest:hamcrest-library:2.2'

    implementation 'org.slf4j:slf4j-api:2.0.5'
    testImplementation 'org.slf4j:slf4j-simple:2.0.5'  // Simple 

    // This dependency is used by the application.
    implementation 'com.google.guava:guava:32.1.2-jre'
    testImplementation 'org.mockito:mockito-core:5.2.0' // Latest version as of 2023
    // If you need to use Mockito with JUnit 5, also add the Mockito JUnit Jupiter extension
    testImplementation 'org.mockito:mockito-junit-jupiter:5.2.0'
    // This dependency is used by the application for CSV reading/writing
    implementation 'com.opencsv:opencsv:5.8'
     testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'  // JUnit for tests
    // This dependency is used by the application for reading/writing Excel Spreadsheets
    implementation 'org.apache.poi:poi:5.2.3','org.apache.poi:poi-ooxml:5.2.3'

}
test {
    testLogging {
        events "passed", "skipped", "failed"
        showStandardStreams = true  // Ensures System.out.println output is displayed
    }
    ignoreFailures = true  // Allows the build to succeed even if tests fail
}


tasks.named('test') {
    useJUnitPlatform()
}


// Javadoc generation task
task generatedocs(type: Javadoc) {
    description = "Generates Javadocs for the project."
    group = "Documentation"
    destinationDir = file("$buildDir/docs/javadoc")
    source = sourceSets.main.allJava
    classpath = sourceSets.main.compileClasspath
}

// Copy Javadocs to another directory
task copydocs(type: Copy) {
    description = "Copies generated Javadocs to the docs directory."
    group = "Documentation"
    dependsOn generatedocs
    from "$buildDir/docs/javadoc"
    into "$rootDir/docs"
    doLast {
        println "Javadocs copied to $rootDir/docs"
}
}